# Beta Diversity analysis
```{r  fig.align = 'center'}
# Load packages
library(vegan)
package.list = c("ade4", "vegan", "viridis", "gplots", "BiodiversityR", "indicspecies")
for (package in package.list) {
  if (!require(package, character.only = TRUE, quietly = TRUE)) {
    install.packages(package, dependencies = TRUE)
    library(package, character.only = TRUE)
  }
}
# Load SbS dataset
data = read.csv("data/SbS_full.csv", row.names= 1)

# Calculate Bray-Curtis distance
data.db = vegdist(data, method = "bray")

site_labels = rownames(data)

################################################3
# Heatmap of dissimilarities 
levelplot(as.matrix(data.db), 
  col.regions = viridis, 
  aspect="iso",
  xlab = "Sites", ylab = "Sites", 
  scales = list(cex=1,
  x=list(labels=site_labels, rot=90), 
  y=list(labels=site_labels)),
  main = "Bray-Curtis Distance")

#############################################################3
# Perform cluster analysis
data.ward = hclust(data.db, method = "ward.D2")

# Plot cluster
par(mar=c(1,5,2,2) + 0.1)
plot(data.ward, main = "Ward's Clustering of SbS data", 
  ylab = "squared Bray_Curtis distance")

######################################################
# PCOA analysis for all sites
data.pcoa = cmdscale(data.db, eig = TRUE, k = 3) 
data.pcoa

# Explained variance for first 3 axes
explained_variance = round(sum(data.pcoa$eig[1:3]/sum(data.pcoa$eig)) * 100, 2)
print("Explained variance of the 3 first axes:")
print(explained_variance)


# Define Plot Parameters
par(mar=c(1,5,2,2) + 0.1)

# Initiate Plot
plot(data.pcoa$points[ ,1], 
  data.pcoa$points[ ,2], 
     xlab = "PCoA 1",
     ylab = "PCoA 2",
     pch = 16, cex = 2,  type = "n", cex.lab = 1.5, 
     cex.axis = 0.5, axes = FALSE)

# # Add Axes
axis(side = 1, labels = T, lwd.ticks = 2, cex.axis = 1.2, las = 1)
axis(side = 2, labels = T, lwd.ticks = 2, cex.axis = 1.2, las = 1)
abline(h = 0, v = 0, lty = 3)
box(lwd = 2)

# # Add Points & Labels
points(data.pcoa$points[ ,1], 
  data.pcoa$points[ ,2],
  pch = 19, cex = 3, bg = "gray", col = "gray")
text(data.pcoa$points[ ,1], data.pcoa$points[ ,2], 
     labels = row.names(data.pcoa$points))
  
# Add species on top
dataREL <- data
  for(i in 1:nrow(data)){
    dataREL[i, ] = data[i, ] / sum(data[i, ])
    } 

# Now, we use this information to calculate and add species scores
data.pcoa <- add.spec.scores(
  data.pcoa,
  dataREL,
  method = "pcoa.scores")

text(
  data.pcoa$cproj[ ,1], 
  data.pcoa$cproj[ ,2], 
  labels = row.names(data.pcoa$cproj), col = "red",
  cex=1)

```

> ***Cluster Analysis***
> 
> We see that some sites cluster consistently by location over different years. For example, site 1 contains all the years sampled, this suggests that the zoobenthos community composition is stable over time. 
> Howeverm some other sites (0 and 2) have some temporal shifts. For instance, site 0_1995 and 0_2002 are clustered closer to sites 2_1994 2_1995, 2_2000, suggesting that there might be environmental changes, disturbances, or shifts in the zoobenthos community composition over time.
>
> ***Bray_Curtis Distance Heatmap***
> We can see shows distinct blocks of similarity between the same site being sampled over years. This was expected. However, we find again that in the early years of site 2 samples (1994,95), site 2 had a zoobenthos biodiversity composition more similar to site 0 of the same year. 
> In conclusion, for sites that show changes over time, we can think that they are locaed in more disturbed areas or are more exposed to environmental changes (pollutionm climate changes, invasive species?)
>
> ***PCOA analysis***
> Here, we see that the sites 0, 1, 2 parated across the PCoA space, suggesting they have distinct community compositions.
Site 1 (e.g., 1_1994, 1_1995, 1_1999, etc.) appears to form a tight cluster, which means that they have a relatively stable species composition over time.
> Sites 2 and 0(e.g., 2_1994, 2_1995, etc.) are more dispersed across multiple quadrants. This suggests that "these sites" have bigger variation in community composition.
>

> I think species nearer to the center are more present in most sites. While species far from the origin are more specialized or strongly associated with particular site conditions.
> There are several patterns : 
> Macoma balthica is strongly associated with site 1. This suggest that this species may adapt well in this site' specific condition. 
> Scoloplos armiger and Bylgides sarsi are more abundant in these site 2. 
> Abra alba, Lagis koreni, and Terebellides stroemii are characteristic site 0.
>

# Hypothesis testing